/**
 * 论坛工具函数 | Forum utility functions
 */

/**
 * GitHub emoji 短代码映射表 | GitHub emoji shortcode mapping
 */
const EMOJI_MAP: Record<string, string> = {
    ':speech_balloon:': '💬',
    ':bulb:': '💡',
    ':pray:': '🙏',
    ':raised_hands:': '🙌',
    ':ballot_box:': '🗳️',
    ':rocket:': '🚀',
    ':bug:': '🐛',
    ':sparkles:': '✨',
    ':memo:': '📝',
    ':question:': '❓',
    ':fire:': '🔥',
    ':star:': '⭐',
    ':heart:': '❤️',
    ':thumbsup:': '👍',
    ':warning:': '⚠️',
    ':book:': '📖',
    ':wrench:': '🔧',
    ':gear:': '⚙️',
    ':zap:': '⚡',
    ':art:': '🎨',
    ':package:': '📦',
    ':lock:': '🔒',
    ':tada:': '🎉',
    ':wave:': '👋',
    ':eyes:': '👀',
    ':thinking:': '🤔',
    ':100:': '💯',
    ':clap:': '👏',
    ':hammer_and_wrench:': '🛠️',
    ':world_map:': '🗺️',
    ':video_game:': '🎮',
    ':computer:': '💻',
    ':pencil:': '✏️',
    ':pencil2:': '✏️',
    ':notebook:': '📓',
    ':clipboard:': '📋',
    ':pushpin:': '📌',
    ':loudspeaker:': '📢',
    ':mega:': '📣',
    ':bell:': '🔔',
    ':email:': '📧',
    ':mailbox:': '📫',
    ':inbox_tray:': '📥',
    ':outbox_tray:': '📤',
    ':file_folder:': '📁',
    ':open_file_folder:': '📂',
    ':card_index:': '📇',
    ':chart_with_upwards_trend:': '📈',
    ':chart_with_downwards_trend:': '📉',
    ':bar_chart:': '📊',
    ':date:': '📅',
    ':calendar:': '📆',
    ':card_index_dividers:': '🗂️',
    ':triangular_ruler:': '📐',
    ':straight_ruler:': '📏',
    ':scissors:': '✂️',
    ':link:': '🔗',
    ':paperclip:': '📎',
    ':hourglass:': '⌛',
    ':watch:': '⌚',
    ':alarm_clock:': '⏰',
    ':stopwatch:': '⏱️',
    ':timer_clock:': '⏲️',
    ':telephone:': '☎️',
    ':telephone_receiver:': '📞',
    ':pager:': '📟',
    ':fax:': '📠',
    ':battery:': '🔋',
    ':electric_plug:': '🔌',
    ':desktop_computer:': '🖥️',
    ':printer:': '🖨️',
    ':keyboard:': '⌨️',
    ':computer_mouse:': '🖱️',
    ':trackball:': '🖲️',
    ':minidisc:': '💽',
    ':floppy_disk:': '💾',
    ':cd:': '💿',
    ':dvd:': '📀',
    ':abacus:': '🧮',
    ':movie_camera:': '🎥',
    ':film_strip:': '🎞️',
    ':film_projector:': '📽️',
    ':clapper:': '🎬',
    ':tv:': '📺',
    ':camera:': '📷',
    ':camera_flash:': '📸',
    ':video_camera:': '📹',
    ':mag:': '🔍',
    ':mag_right:': '🔎',
    ':candle:': '🕯️',
    ':bulb_lightbulb:': '💡',
    ':flashlight:': '🔦',
    ':izakaya_lantern:': '🏮',
    ':diya_lamp:': '🪔',
    ':notebook_with_decorative_cover:': '📔',
    ':closed_book:': '📕',
    ':green_book:': '📗',
    ':blue_book:': '📘',
    ':orange_book:': '📙',
    ':books:': '📚',
    ':ledger:': '📒',
    ':page_with_curl:': '📃',
    ':scroll:': '📜',
    ':page_facing_up:': '📄',
    ':newspaper:': '📰',
    ':rolled_up_newspaper:': '🗞️',
    ':bookmark_tabs:': '📑',
    ':bookmark:': '🔖',
    ':label:': '🏷️',
    ':moneybag:': '💰',
    ':coin:': '🪙',
    ':yen:': '💴',
    ':dollar:': '💵',
    ':euro:': '💶',
    ':pound:': '💷',
    ':money_with_wings:': '💸',
    ':credit_card:': '💳',
    ':receipt:': '🧾',
    ':chart:': '💹',
};

/**
 * 转换 GitHub emoji 短代码为 Unicode | Convert GitHub emoji shortcode to Unicode
 */
export function parseEmoji(emojiCode: string | undefined | null): string {
    if (!emojiCode) return '💬';
    // 如果已经是 emoji，直接返回 | If already emoji, return directly
    if (!emojiCode.startsWith(':')) return emojiCode;
    return EMOJI_MAP[emojiCode] || emojiCode.replace(/:/g, '');
}
