pub mod entity;
pub mod component;
pub mod entity_manager;
pub mod query_system;
pub mod scene;
pub mod systems;
pub mod events;
pub mod archetype_system;
pub mod fluent_api;
pub mod passive_system;
pub mod component_builder;
pub mod entity_batch_operator;
pub mod scene_builder;

pub use entity::Entity;
pub use component::{Component, ComponentRegistry, BaseComponent};
pub use entity_manager::EntityManager;
pub use query_system::{QuerySystem, QueryResult};
pub use scene::Scene;
pub use systems::{System, EntitySystem, ProcessingSystem, IntervalSystem, SystemManager};
pub use events::{ECSEventType, EventPriority, Event, EventListener, EventBus, EventBusStats, SimpleEventListener};
pub use archetype_system::{ArchetypeSystem, Archetype, ArchetypeId, ArchetypeQueryResult, ArchetypeSystemStats};
pub use fluent_api::{EntityBuilder, QueryBuilder, ECSFluentAPI, FluentAPIStats};
pub use passive_system::{PassiveSystem, PassiveSystemBuilder};
pub use component_builder::{ComponentBuilder, BaseComponentBuilder, ComponentBuilderFactory, ComponentBuilderStats};
pub use entity_batch_operator::{EntityBatchOperator, BatchOperatorStats};
pub use scene_builder::{SceneBuilder, SceneTemplate, SceneBuilderStats, SceneBuilderFactory, SceneBuilderManager};